// dev/legal-pages.mjs — put the Terms and the Privacy Policy inside the app.
//
// The two documents are written once, in `landing/`, where they are published at
// daimond.app. The APP is served from another origin, so a link to them from
// inside Daimond is a link off the app — and on daimond.oxedyne.com those two
// paths simply 404. A user asked to accept terms they cannot open has not been
// asked anything.
//
// So the same prose is rendered a second time, as two pages of Daimond's own
// guide site, which the Web panel already shows in-frame:
//
//   www/guide/legal/terms.html      DaimondLegal.open('terms')
//   www/guide/legal/privacy.html    DaimondLegal.open('privacy')
//
// GENERATED, NOT COPIED. A legal document that exists twice is a legal document
// that will differ in one of the two places, and nobody finds out until it
// matters. The article body is lifted verbatim from the landing page at build
// time; `--check` fails if the two have drifted, and `verify_legalreach.mjs`
// runs that check, so an edit to `landing/terms.html` that never reaches the app
// cannot ship.
//
// What changes on the way in, and nothing else changes:
//
//   1. The landing chrome goes. Its header carries a "Launch app" button and its
//      footer a link to the app — both point at another origin, which is the
//      whole defect being fixed. The guide's own header and footer take their
//      place, and every link in the result is same-origin. `verify_legalreach`
//      asserts that at the DOM, not here.
//   2. Anchors with a scheme become plain text. The prose says "the product
//      website is daimond.app"; it still says exactly that, without being a way
//      out of the panel.
//   3. The editorial comments go. `[TO CONFIRM]` is prose and stays, in full and
//      marked: a reader of the draft is entitled to see which parts are open.
//      The LAWYER comments are notes to ourselves about how to close them.
//
//   node dev/legal-pages.mjs            # write
//   node dev/legal-pages.mjs --check    # exit 1 if either page would change

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(HERE, '..');
const FROM = path.join(ROOT, 'landing');
const INTO = path.join(ROOT, 'www', 'guide', 'legal');

/// The two documents, and how each names itself in the app.
export const DOCS = [
	{ file: 'terms.html',   title: 'Terms of Service' },
	{ file: 'privacy.html', title: 'Privacy Policy' },
];

/// The one part of a landing page that is the document: everything between the
/// `<main>` tags. Throws rather than guesses — a page whose shape has changed
/// must be looked at, not silently half-published.
function article(src, file) {
	const m = /<main>\n([\s\S]*?)\n<\/main>/.exec(src);
	if (!m) throw new Error(`${file}: no <main> … </main> to take the document from`);
	return m[1];
}

/// The DRAFT banner, taken from the page rather than restated here, so the two
/// cannot come to say different things about the same draft.
function banner(src, file) {
	const m = /<div class="draft-banner"[\s\S]*?<\/div>/.exec(src);
	if (!m) throw new Error(`${file}: no DRAFT banner`);
	return m[0];
}

/// Strip our own editorial comments.
function decomment(html) {
	return html.replace(/<!--[\s\S]*?-->\n?/g, '');
}

/// Turn every anchor that leaves this origin into the words it wrapped.
///
/// Anything with a scheme (`https:`, `mailto:`) or protocol-relative (`//host`).
/// A same-page `#anchor` and a sibling `privacy.html` are left alone: both
/// resolve inside the frame, which is the point.
function unlink(html) {
	return html.replace(/<a\s+href="(?:[a-z][a-z0-9+.-]*:|\/\/)[^"]*"[^>]*>([\s\S]*?)<\/a>/gi,
		(m, text) => text);
}

/// The head of the generated file: which of the two it is, and where its sibling
/// sits. All same-origin, all relative to `www/guide/legal/`.
function page(doc, bannerHtml, body) {
	return `<!-- GENERATED by dev/legal-pages.mjs from landing/${doc.file}. Do not edit:
     edit the landing page and run the generator. dev/verify_legalreach.mjs fails
     if this file and its source have drifted apart. -->
<!DOCTYPE html>
<html lang="en-GB" data-guide-locale="en" data-guide-locales="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
<title>${doc.title} — Daimond</title>
<link rel="icon" type="image/svg+xml" href="../../assets/daimond_mark.svg">
<link rel="stylesheet" href="../../css/variables.css">
<link rel="stylesheet" href="../../css/guide.css">
<link rel="stylesheet" href="../../css/legal.css">
<script src="../frame.js"></script>
</head>
<body class="legal-page">

<header class="site-head">
\t<div class="site-head-inner">
\t\t<a class="brand" href="../index.html" aria-label="Daimond guide, home">
\t\t\t<img class="wordmark wm-dark" src="../../assets/daimond_word.svg" alt="Daimond" translate="no">
\t\t\t<img class="wordmark wm-light" src="../../assets/daimond_word_dark.svg" alt="" aria-hidden="true" translate="no">
\t\t\t<span class="brand-sub">Legal</span>
\t\t</a>
\t\t<nav class="site-nav" aria-label="Legal documents">
\t\t\t<a href="terms.html"${doc.file === 'terms.html' ? ' aria-current="page"' : ''}>Terms of Service</a>
\t\t\t<a href="privacy.html"${doc.file === 'privacy.html' ? ' aria-current="page"' : ''}>Privacy Policy</a>
\t\t\t<a href="../index.html">User guide</a>
\t\t</nav>
\t</div>
\t${bannerHtml.replace(/\n/g, '\n\t')}
</header>

<main>
${body}
</main>

<footer class="site-foot">
\t<span>In force from 13 August 2026. Points marked [TO CONFIRM] are still being settled, and no lawyer has reviewed these documents.</span>
\t<nav aria-label="Legal documents">
\t\t<a href="terms.html">Terms of Service</a>
\t\t<a href="privacy.html">Privacy Policy</a>
\t\t<a href="../index.html">User guide</a>
\t</nav>
</footer>
</body>
</html>
`;
}

/// Build one page, as bytes.
export function build(doc) {
	const src = fs.readFileSync(path.join(FROM, doc.file), 'utf8');
	const body = unlink(decomment(article(src, doc.file)));
	return page(doc, decomment(banner(src, doc.file)), body);
}

/// Write, or say what would change.
function main() {
	const check = process.argv.includes('--check');
	let moved = 0;
	fs.mkdirSync(INTO, { recursive: true });
	for (const doc of DOCS) {
		const to   = path.join(INTO, doc.file);
		const want = build(doc);
		const have = fs.existsSync(to) ? fs.readFileSync(to, 'utf8') : null;
		if (have === want) { console.log(`  ok      guide/legal/${doc.file}`); continue; }
		moved++;
		if (check) {
			console.log(`  STALE   guide/legal/${doc.file} — ${have === null
				? 'has never been generated' : 'differs from landing/' + doc.file}`);
		} else {
			fs.writeFileSync(to, want);
			console.log(`  written guide/legal/${doc.file} (${want.length} bytes)`);
		}
	}
	if (check && moved) {
		console.log('\nRun `node dev/legal-pages.mjs` to bring the in-app pages up to date.');
		process.exit(1);
	}
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url))) {
	main();
}
