#!/usr/bin/env bash
# refresh.sh -- rebuild the vendored Typst packages under `packs/` from a local
# typst package cache.
#
# It is shipped BESIDE what it produces, and served with it, deliberately: the
# packs are sealed into `www/manifest.json` and the transparency chain, so the
# recipe that made them belongs inside the same seal. A reader with the same
# package cache runs this and gets the same bytes.
#
#   bash www/assets/typst/refresh.sh                    # from ~/.cache/typst/packages
#   TYPST_CACHE=/some/where bash .../refresh.sh         # from another cache
#
# NOTHING IS DOWNLOADED. The cache is read; if a package named below is not in
# it, this script says so and stops rather than writing a set that is missing one.
#
# After running it, `www/assets/typst/packs/INDEX` has changed, and that file is
# `include_str!`d by `src/wasm/typst.rs` -- so the wasm must be rebuilt and the
# bundle resealed, or the wasm and the served packs describe different sets.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CACHE="${TYPST_CACHE:-$HOME/.cache/typst/packages}"
OUT="$HERE/packs"

# ── The set, and why each member is in it ───────────────────────────────────
#
# Namespace, name, version. Order is the order the INDEX lists them in, and the
# INDEX is what a refusal reads out, so it is the order a person sees.
#
#   cetz 0.3.4       the author's own book imports it; the whole reason for this
#   oxifmt 0.2.1     cetz 0.3.4 imports it, and cetz 0.3.2 does too
#   cetz 0.3.2       cetz-plot 0.1.1 imports THIS version, not 0.3.4
#   cetz-plot 0.1.1  charts and plots on top of cetz
#   fletcher 0.5.7   arrow diagrams; imports cetz 0.3.4
#
# cetz appears twice on purpose. A closure is not a wish list: cetz-plot names
# `@preview/cetz:0.3.2` in `src/cetz.typ`, so shipping cetz-plot without 0.3.2
# would ship a package that resolves and then fails on its own dependency --
# which is the one failure this whole mechanism is written to make impossible to
# mistake for something else.
SET=(
	"preview cetz 0.3.4"
	"preview oxifmt 0.2.1"
	"preview cetz 0.3.2"
	"preview cetz-plot 0.1.1"
	"preview fletcher 0.5.7"
)

# ── What is taken from each package ─────────────────────────────────────────
#
# The sources, the manifest that names the entrypoint, and the licence. Not the
# README, not the gallery, not a built PDF: they are never read by a compile and
# they are the bulk of what a package directory weighs. The licence IS taken --
# these are other people's LGPL and MIT work and it ships inside our bundle.
want() {
	local root="$1"
	( cd "$root" && find . -type f \
		\( -name '*.typ' -o -name 'typst.toml' -o -name 'LICENSE' -o -name 'LICENSE.*' \) \
		-printf '%P\n' | LC_ALL=C sort )
}

rm -rf "$OUT"
mkdir -p "$OUT"
INDEX="$OUT/INDEX"

{
	echo "# Typst packages vendored into Daimond. Generated by www/assets/typst/refresh.sh."
	echo "# One line per pack: namespace name version file-count pack-bytes."
	echo "# The packs are at packs/<namespace>/<name>/<version>.pack."
} > "$INDEX"

for entry in "${SET[@]}"; do
	read -r ns name ver <<< "$entry"
	src="$CACHE/$ns/$name/$ver"
	if [ ! -d "$src" ]; then
		echo "refresh.sh: $ns/$name:$ver is not in $CACHE -- nothing written." >&2
		exit 1
	fi
	entrypoint="$(sed -n 's/^[[:space:]]*entrypoint[[:space:]]*=[[:space:]]*"\(.*\)".*/\1/p' "$src/typst.toml" | head -1)"
	if [ -z "$entrypoint" ]; then
		echo "refresh.sh: $ns/$name:$ver has no entrypoint in its typst.toml." >&2
		exit 1
	fi

	mapfile -t files < <(want "$src")
	if [ "${#files[@]}" -eq 0 ]; then
		echo "refresh.sh: $ns/$name:$ver holds no sources." >&2
		exit 1
	fi

	dest="$OUT/$ns/$name"
	mkdir -p "$dest"
	pack="$dest/$ver.pack"

	# The header: ASCII lines, then ONE blank line, then the file bodies
	# concatenated in the order listed. Lengths rather than delimiters, so a
	# source containing anything at all cannot end a file early.
	{
		echo "DAIMOND TYPST PACK 1"
		echo "namespace $ns"
		echo "name $name"
		echo "version $ver"
		echo "entrypoint $entrypoint"
		for f in "${files[@]}"; do
			echo "file $(stat -c%s "$src/$f") $f"
		done
		echo
	} > "$pack"
	for f in "${files[@]}"; do
		cat "$src/$f" >> "$pack"
	done

	echo "pack $ns $name $ver ${#files[@]} $(stat -c%s "$pack")" >> "$INDEX"
	echo "packed $ns/$name:$ver -- ${#files[@]} files, $(stat -c%s "$pack") bytes"
done

echo
echo "INDEX:"
cat "$INDEX"
echo
echo "src/wasm/typst.rs include_str!s that INDEX -- rebuild the wasm and reseal."
