//! The deletion meter: every removal a fenced command makes, held in the kernel while the
//! hand decides whether it counts.
//!
//! Built 2026-09-23 from `daimond_hand_delete_fence_design_20260923.md`, section 4.2 and
//! 4.3, after a daimon's command emptied a Diamond on 2026-09-22.  Landlock cannot refuse
//! removal inside a mark without breaking git and every atomic save, so the fence alone
//! lets a command empty a mark; this module is the part that does not.
//!
//! The launcher installs a second seccomp filter that answers `SCMP_ACT_NOTIFY` for
//! `unlink`, `unlinkat`, `rmdir`, `rename`, `renameat` and `renameat2`.  The hand takes the
//! listener with `pidfd_getfd` before the command exists, and [`watch`] answers each call:
//! let it through, refuse it, or -- once the turn's [`BUDGET`] of pre-existing files is
//! spent -- leave it unanswered, so the command sits blocked in the kernel until the user
//! says whether it may go on.  Every counted file is hard-linked into a trash outside the
//! fence first, so what does go can be put back.  Where the mark is on another filesystem the
//! file is copied instead, up to [`COPY_MAX`], and a larger one is not removed at all (audit F6).
//!
//! The filter needs the `libseccomp` crate, a safe binding over the system's
//! `libseccomp.so.2`, which the owner approved on 2026-09-23: `seccompiler` has no notify
//! action, rustix does not wrap seccomp, and the hand writes no `unsafe`.
//!
//! A rename onto a file that was there before the turn is counted too, as a removal of the
//! file it replaces, and that file is kept first (audit F3, 2026-09-23).
//!
//! Holes, stated rather than left to be found, and both Phase 2 of the design: a file
//! emptied or overwritten in place (`O_TRUNC`, `truncate`, `dd`, a write over it) loses its
//! old bytes through no call this filter holds, so it is neither counted nor kept; and the
//! path is read from the caller's memory, so a second thread rewriting it between the check
//! and the kernel's own read could make a counted removal look free.  The COUNT of calls
//! cannot be raced; only the classification can.

use crate::wire::{
    Resp,
    Sig,
};

use oxedyne_fe2o3_core::prelude::*;

use std::{
    collections::HashSet,
    path::{
        Component,
        Path,
        PathBuf,
    },
    sync::{
        atomic::{
            AtomicBool,
            AtomicU32,
            Ordering,
        },
        Arc,
    },
    time::{
        Duration,
        SystemTime,
        UNIX_EPOCH,
    },
};

/// Pre-existing files a turn may remove before the user is asked.
pub const BUDGET: u32 = 64;

/// How long a held command waits for an answer before it is stopped.
pub const HOLD_MS: u64 = 120_000;

/// How long the trash keeps a turn's files.
pub const TRASH_KEEP: Duration = Duration::from_secs(7 * 24 * 3600);

/// Where the trash lives, when the operator says so.
pub const TRASH_DIR_VAR: &str = "DAIMOND_HAND_TRASH_DIR";

/// The calls the meter holds.  A name this architecture lacks is skipped.
pub const METERED: &[&str] = &["unlink", "unlinkat", "rmdir", "rename", "renameat", "renameat2"];

/// Directories whose contents are regenerated by a tool and so are not counted.
const CACHE_NAMES: &[&str] = &["node_modules", "__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache"];

/// What `/proc/<pid>/fd/<n>` reads as for a seccomp listener.
const LISTENER_LINK: &str = "anon_inode:seccomp notify";

const AT_FDCWD:     i32 = -100;
const AT_REMOVEDIR: u64 = 0x200;
const RENAME_NOREPLACE: u64 = 1;	// renameat2: fail rather than replace
const RENAME_EXCHANGE:  u64 = 2;	// renameat2: swap the two, losing neither
const PATH_READ_MAX: usize = 4096;
const NOTES_MAX:     usize = 8;	// readable refusals sent per run, so a loop cannot flood the page
const SAMPLE_MAX:    usize = 5;

// Copying in place of a link
//
// A counted file is hard-linked into the trash, which costs nothing.  Where the mark is on a
// different filesystem from the trash the link fails, and the only way to keep the file is to
// copy it -- which costs its whole size, in trash space and in time spent with the command
// blocked in the kernel.  So only a file this small is copied: the page's own
// `VERSION_FILE_MAX`, which the design named for exactly this (§4.3, audit F6).
pub const COPY_MAX: u64 = 512 * 1024;

/// What one run's meter found, read by the supervisor when the run ends.
#[derive(Debug, Default)]
pub struct Tally {
    pub counted: AtomicU32,
    pub stopped: AtomicBool,
}

/// What one run's meter is told.
#[derive(Clone, Debug)]
pub struct Watch {
    pub id:       String,
    pub marks:    Vec<PathBuf>,	// canonical roots whose pre-existing files are counted
    pub caches:   Vec<PathBuf>,	// canonical toolchain caches, free wherever a mark holds one
    pub budget:   u32,			// counted removals left this turn
    pub since:    SystemTime,	// the turn's start: a file born after it is free
    pub since_ms: u64,			// the same, as the page named it, which keys the trash
    pub trash:    PathBuf,		// the trash root, outside every fence
}

impl Watch {

    /// The turn start as a time, from the page's milliseconds.
    pub fn since_of(ms: u64) -> SystemTime {
        UNIX_EPOCH + Duration::from_millis(ms)
    }

    /// Now, in the page's milliseconds.
    pub fn now_ms() -> u64 {
        match SystemTime::now().duration_since(UNIX_EPOCH) {
            Ok(d)  => d.as_millis() as u64,
            Err(_) => 0,
        }
    }
}

/// Where the trash lives: beside the journal and the scratch, and never inside a fence.
pub fn trash_root() -> Outcome<PathBuf> {
    if let Ok(v) = std::env::var(TRASH_DIR_VAR) {
        if !v.is_empty() {
            return Ok(PathBuf::from(v));
        }
    }
    if let Ok(x) = std::env::var("XDG_DATA_HOME") {
        if !x.is_empty() {
            return Ok(Path::new(&x).join("daimond/hand/trash"));
        }
    }
    match std::env::var("HOME") {
        Ok(h) if !h.is_empty() => Ok(Path::new(&h).join(".local/share/daimond/hand/trash")),
        _ => Err(err!(
            "Neither XDG_DATA_HOME nor HOME is set, so the hand cannot say where removed files \
            are kept. Set {}.", TRASH_DIR_VAR;
            Missing, Configuration, Path)),
    }
}

/// Removes turns older than [`TRASH_KEEP`].  Best effort: a failure leaves a turn for the
/// next sweep.
pub fn sweep(root: &Path) {
    let rd = match std::fs::read_dir(root) {
        Ok(rd) => rd,
        Err(_) => return,
    };
    let now = SystemTime::now();
    for e in rd.flatten() {
        let old = match e.metadata().and_then(|m| m.modified()) {
            Ok(t)  => now.duration_since(t).map(|d| d > TRASH_KEEP).unwrap_or(false),
            Err(_) => false,
        };
        if old {
            let _ = std::fs::remove_dir_all(e.path());
        }
    }
}

/// Puts back every file the meter took during the turn `since_ms`.
///
/// A file whose original path is occupied again is left in the trash and counted as
/// skipped: something now stands there, and overwriting it would be a second loss.
///
/// # Returns
/// `(restored, skipped)`.
pub fn restore(root: &Path, since_ms: u64) -> Outcome<(u32, u32)> {
    let turn = root.join(fmt!("{}", since_ms));
    if !turn.is_dir() {
        return Err(err!(
            "There is nothing in the trash for the turn that began at {} ms: either nothing was \
            removed then, or it has been more than seven days.", since_ms;
            NotFound, Path));
    }
    // Layer 0 first: a path taken twice in one turn is put back as it was the first time.
    let mut layers: Vec<(u64, PathBuf)> = Vec::new();
    for e in res!(std::fs::read_dir(&turn)).flatten() {
        if let Ok(k) = e.file_name().to_string_lossy().parse::<u64>() {
            layers.push((k, e.path()));
        }
    }
    layers.sort();
    let mut n = (0u32, 0u32);
    for (_, layer) in &layers {
        res!(put_back(layer, layer, &mut n));
    }
    let _ = remove_empty(&turn);
    Ok(n)
}

fn put_back(turn: &Path, dir: &Path, n: &mut (u32, u32)) -> Outcome<()> {
    let rd = res!(std::fs::read_dir(dir));
    for e in rd {
        let e = res!(e);
        let p = e.path();
        let ft = res!(e.file_type());
        if ft.is_dir() {
            res!(put_back(turn, &p, n));
            continue;
        }
        let rel = match p.strip_prefix(turn) {
            Ok(r)  => r,
            Err(_) => continue,
        };
        // Only plain names: the trash is written by this module alone, and a path that
        // is anything else was not.
        if rel.components().any(|c| !matches!(c, Component::Normal(_))) {
            n.1 += 1;
            continue;
        }
        let orig = Path::new("/").join(rel);
        if std::fs::symlink_metadata(&orig).is_ok() {
            n.1 += 1;
            continue;
        }
        if let Some(parent) = orig.parent() {
            res!(std::fs::create_dir_all(parent));
        }
        let moved = match std::fs::rename(&p, &orig) {
            Ok(()) => true,
            Err(_) => std::fs::copy(&p, &orig).is_ok() && std::fs::remove_file(&p).is_ok(),
        };
        if moved { n.0 += 1; } else { n.1 += 1; }
    }
    Ok(())
}

fn remove_empty(dir: &Path) -> bool {
    let rd = match std::fs::read_dir(dir) {
        Ok(rd) => rd,
        Err(_) => return false,
    };
    let mut empty = true;
    for e in rd.flatten() {
        let p = e.path();
        if !(p.is_dir() && remove_empty(&p)) {
            empty = false;
        }
    }
    empty && std::fs::remove_dir(dir).is_ok()
}

// ┌───────────────────────────────────────────────────────────────┐
// │ Classifying one call                                           │
// └───────────────────────────────────────────────────────────────┘

/// What to answer one held call with.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum Verdict {
    Go,						// let it through, uncounted
    Root(PathBuf),			// a root, or a directory holding one: refused with EPERM
    Count(PathBuf, PathBuf),	// a pre-existing file under a mark: (victim, mark)
    Xdev,					// a counted file renamed out of the counted zone: EXDEV, so it is copied and unlinked
}

/// Decides calls against one run's marks.  Kept apart from the kernel so it can be
/// tested without one.
pub struct Judge {
    marks:  Vec<PathBuf>,
    caches: Vec<PathBuf>,		// toolchain caches, free where a mark holds one
    since:  SystemTime,
    zones:  HashSet<PathBuf>,	// `target` directories seen holding CACHEDIR.TAG this run
}

impl Judge {

    pub fn new(marks: Vec<PathBuf>, caches: Vec<PathBuf>, since: SystemTime) -> Self {
        Self { marks, caches, since, zones: HashSet::new() }
    }

    fn mark_of(&self, p: &Path) -> Option<PathBuf> {
        self.marks.iter()
            .filter(|m| p.starts_with(m))
            .max_by_key(|m| m.as_os_str().len())
            .cloned()
    }

    /// Is `p` a root, or a directory with a root inside it?
    fn holds_root(&self, p: &Path) -> bool {
        self.marks.iter().any(|m| m.starts_with(p))
    }

    /// Is `p` inside a cache a tool regenerates?  The mark root itself never is.
    fn regenerable(&mut self, p: &Path, mark: &Path) -> bool {
        let rel = match p.strip_prefix(mark) {
            Ok(r)  => r,
            Err(_) => return false,
        };
        // A toolchain cache the mark HOLDS -- `~/.cache/cargo-targets` in a granted home
        // directory.  Never one that holds the mark: a Diamond's folder kept under
        // `~/.cache/daimond` is the user's work, and is counted like any other (audit F5).
        if self.caches.iter().any(|c| c != mark && c.starts_with(mark) && p.starts_with(c)) {
            return true;
        }
        let mut at = mark.to_path_buf();
        let n = rel.components().count();
        for (i, c) in rel.components().enumerate() {
            // Ancestors only: the entry itself is what is being removed.
            if i + 1 >= n {
                break;
            }
            at.push(c.as_os_str());
            let name = c.as_os_str().to_string_lossy();
            if CACHE_NAMES.contains(&name.as_ref()) {
                return true;
            }
            // Cargo writes the tag into every target directory. Remembered once seen,
            // because `rm -rf target` may take the tag before the rest.
            if name == "target" {
                if self.zones.contains(&at) {
                    return true;
                }
                if at.join("CACHEDIR.TAG").is_file() {
                    self.zones.insert(at.clone());
                    return true;
                }
            }
        }
        false
    }

    fn born_this_turn(&self, p: &Path) -> bool {
        match std::fs::symlink_metadata(p).and_then(|m| m.created()) {
            Ok(t)  => t >= self.since,
            // No birth time, or no file: counted, which is the safe direction.
            Err(_) => false,
        }
    }

    /// An `unlink` or an `rmdir` of `p`.
    pub fn remove(&mut self, p: &Path, is_dir: bool) -> Verdict {
        if self.holds_root(p) {
            return Verdict::Root(p.to_path_buf());
        }
        let mark = match self.mark_of(p) {
            Some(m) => m,
            None    => return Verdict::Go,
        };
        // Nothing there: the kernel answers ENOENT, and git asks this routinely.
        if std::fs::symlink_metadata(p).is_err() {
            return Verdict::Go;
        }
        // An empty directory holds no bytes.
        if is_dir || self.regenerable(p, &mark) || self.born_this_turn(p) {
            return Verdict::Go;
        }
        Verdict::Count(p.to_path_buf(), mark)
    }

    /// A rename of `from` to `to`.
    ///
    /// Two losses hide in a rename.  A counted file moved out of the counted zone is a
    /// removal in disguise, answered [`Verdict::Xdev`].  And a rename onto a file that was
    /// there before the turn destroys that file exactly as an `unlink` would -- `mv -f`,
    /// `sed -i` and every editor's atomic save replace this way -- so the file replaced is
    /// counted, and kept, like one.  Keyed on the source alone, as it was until the audit
    /// of 2026-09-23 (F3), `mv -f <new> <old>` took `<old>` uncounted.
    ///
    /// # Arguments
    /// * `flags` - `renameat2`'s flags, 0 for the other two calls.  An exchange keeps both
    ///   files and a no-replace rename fails rather than replace, so neither loses `to`.
    pub fn rename(&mut self, from: &Path, to: &Path, flags: u64) -> Verdict {
        for p in [from, to] {
            if self.holds_root(p) {
                return Verdict::Root(p.to_path_buf());
            }
        }
        // Nothing to move: the kernel answers ENOENT and nothing at `to` is touched.
        let src = match std::fs::symlink_metadata(from) {
            Ok(m)  => m,
            Err(_) => return Verdict::Go,
        };
        let exchange = flags & RENAME_EXCHANGE != 0;
        // An exchange moves both files, so either may be the one leaving.
        if self.leaves_zone(from, to) || (exchange && self.leaves_zone(to, from)) {
            return Verdict::Xdev;
        }
        if exchange || flags & RENAME_NOREPLACE != 0 || src.is_dir() {
            // A directory replaces only an empty directory, which holds nothing.
            return Verdict::Go;
        }
        self.replaced(to, &src)
    }

    /// Would moving `from` to `to` take a counted file out of the counted zone: into a
    /// cache, which a later `rm -rf` empties for free, or out of the marks altogether?
    fn leaves_zone(&mut self, from: &Path, to: &Path) -> bool {
        let mark = match self.mark_of(from) {
            Some(m) => m,
            None    => return false,
        };
        if std::fs::symlink_metadata(from).is_err()
            || self.regenerable(from, &mark)
            || self.born_this_turn(from)
        {
            return false;
        }
        match self.mark_of(to) {
            Some(to_mark) => self.regenerable(to, &to_mark),
            None          => true,
        }
    }

    /// What replacing `to` with the file `src` describes costs: a counted removal where
    /// `to` is a file that was there before the turn, under a mark and outside a cache.
    fn replaced(&mut self, to: &Path, src: &std::fs::Metadata) -> Verdict {
        let mark = match self.mark_of(to) {
            Some(m) => m,
            None    => return Verdict::Go,
        };
        let old = match std::fs::symlink_metadata(to) {
            Ok(m)  => m,
            Err(_) => return Verdict::Go,	// nothing stands there
        };
        // A directory cannot be replaced by a file, and two names for one inode is a
        // rename the kernel carries out as nothing at all.
        if old.is_dir() || same_inode(&old, src) {
            return Verdict::Go;
        }
        if self.regenerable(to, &mark) || self.born_this_turn(to) {
            return Verdict::Go;
        }
        Verdict::Count(to.to_path_buf(), mark)
    }
}

/// Are these two names for one inode?
#[cfg(unix)]
fn same_inode(a: &std::fs::Metadata, b: &std::fs::Metadata) -> bool {
    use std::os::unix::fs::MetadataExt;
    a.dev() == b.dev() && a.ino() == b.ino()
}

#[cfg(not(unix))]
fn same_inode(_a: &std::fs::Metadata, _b: &std::fs::Metadata) -> bool {
    false
}

/// Where a counted file goes before it is removed: under the turn, then a layer, then its
/// own absolute path.
fn trash_path(trash: &Path, since_ms: u64, layer: u32, victim: &Path) -> PathBuf {
    let mut out = trash.join(fmt!("{}", since_ms)).join(fmt!("{}", layer));
    for c in victim.components() {
        if let Component::Normal(n) = c {
            out.push(n);
        }
    }
    out
}

/// Links `victim` into the trash, or copies it where the link cannot be made.
///
/// An error is a removal refused: what the trash does not hold cannot be put back, and every
/// sentence the hand and the page say about a counted removal says that it can.  The design
/// counted an oversized file twice and let it go uncopied (§4.3); that loses it for good, which
/// is why a file too large to copy is refused instead (audit F6).
fn keep(trash: &Path, since_ms: u64, victim: &Path) -> Outcome<()> {
    // The same path taken twice in one turn keeps both, a layer apart.
    let mut layer = 0;
    let mut dest = trash_path(trash, since_ms, layer, victim);
    while std::fs::symlink_metadata(&dest).is_ok() {
        layer += 1;
        dest = trash_path(trash, since_ms, layer, victim);
    }
    if let Some(parent) = dest.parent() {
        res!(std::fs::create_dir_all(parent));
    }
    match std::fs::hard_link(victim, &dest) {
        Ok(()) => Ok(()),
        Err(_) => copy_kept(victim, &dest),
    }
}

/// Keeps `victim` at `dest` by copying it, for a file the trash could not link.
fn copy_kept(victim: &Path, dest: &Path) -> Outcome<()> {
    let meta = res!(std::fs::symlink_metadata(victim).map_err(|e| err!(e,
        "it could not be read to be kept"; IO, File)));
    // A link holds a path and is kept as the same path.  Copying THROUGH it would keep whatever
    // it points at, read from wherever that is, and put a file back where a link had been.
    if meta.file_type().is_symlink() {
        return keep_link(victim, dest);
    }
    // A pipe or a socket holds no bytes to keep, and opening one to copy it can wait for ever.
    if !meta.is_file() {
        return Err(err!(
            "it is neither a file nor a link, so the trash cannot hold a copy of it"; Invalid, File));
    }
    if meta.len() > COPY_MAX {
        return Err(err!(
            "it is {} bytes on a different filesystem from the hand's trash, so it could be kept \
            only by copying it, and the hand copies nothing over {} bytes. The user can remove \
            it themselves", meta.len(), COPY_MAX; TooBig, File));
    }
    res!(std::fs::copy(victim, dest).map_err(|e| err!(e,
        "it could not be copied into the hand's trash"; IO, File)));
    Ok(())
}

#[cfg(unix)]
fn keep_link(victim: &Path, dest: &Path) -> Outcome<()> {
    let to = res!(std::fs::read_link(victim).map_err(|e| err!(e,
        "the link could not be read to be kept"; IO, File)));
    res!(std::os::unix::fs::symlink(&to, dest).map_err(|e| err!(e,
        "the link could not be kept in the hand's trash"; IO, File)));
    Ok(())
}

#[cfg(not(unix))]
fn keep_link(_victim: &Path, _dest: &Path) -> Outcome<()> {
    Err(err!("a link cannot be kept on this platform"; Unimplemented, File))
}

// ┌───────────────────────────────────────────────────────────────┐
// │ The kernel half (Linux)                                        │
// └───────────────────────────────────────────────────────────────┘

/// Installs the notify filter on the calling process and returns the listener's number.
///
/// Called by the launcher after the fence and the deny-list, immediately before `exec`.
/// The context is returned as well and must outlive the `exec`, so that nothing closes
/// the listener before the hand has taken its copy.
#[cfg(target_os = "linux")]
pub fn install() -> Outcome<(libseccomp::ScmpFilterContext, i32)> {
    use libseccomp::{
        ScmpAction,
        ScmpFilterContext,
        ScmpSyscall,
    };
    let mut ctx = res!(ScmpFilterContext::new(ScmpAction::Allow).map_err(|e| err!(
        "The deletion meter's filter could not be created: {}.", e; System, Init)));
    let mut n = 0;
    for name in METERED {
        let sc = match ScmpSyscall::from_name(name) {
            Ok(s)  => s,
            Err(_) => continue, // Absent on this architecture: aarch64 has no `unlink`.
        };
        res!(ctx.add_rule(ScmpAction::Notify, sc).map_err(|e| err!(
            "The deletion meter could not hold {}: {}.", name, e; System, Init)));
        n += 1;
    }
    if n == 0 {
        return Err(err!("The deletion meter found none of the removal calls on this \
            architecture, so it would meter nothing."; System, Unimplemented));
    }
    res!(ctx.load().map_err(|e| err!(
        "The deletion meter's filter could not be installed: {}. It needs Linux 5.5 and \
        libseccomp 2.5.", e; System, Init)));
    let fd = res!(ctx.get_notify_fd().map_err(|e| err!(
        "The deletion meter's filter gave no listener: {}.", e; System, Init)));
    Ok((ctx, fd))
}

/// Takes a copy of the launcher's listener, waiting up to `wait` for it to appear.
///
/// The launcher reports nothing: it has no channel of its own that is not also the
/// command's.  So the hand looks, in `/proc/<pid>/fd`, for the one descriptor that reads
/// as a seccomp listener, and copies it with `pidfd_getfd` -- allowed because the hand is
/// the launcher's parent.
#[cfg(target_os = "linux")]
pub fn grab(pid: u32, wait: Duration) -> Outcome<std::os::fd::OwnedFd> {
    use rustix::process::{
        pidfd_getfd,
        pidfd_open,
        Pid,
        PidfdFlags,
        PidfdGetfdFlags,
    };
    let dir = PathBuf::from(fmt!("/proc/{}/fd", pid));
    let until = std::time::Instant::now() + wait;
    loop {
        // A launcher that has gone, or died, will never install anything.
        let rd = match std::fs::read_dir(&dir) {
            Ok(rd) => rd,
            Err(e) => return Err(err!(
                "The launcher {} ended before it installed the deletion meter ({}).", pid, e;
                System, Missing)),
        };
        let stat = std::fs::read_to_string(fmt!("/proc/{}/stat", pid)).unwrap_or_default();
        let state = stat.rsplit(") ").next().and_then(|s| s.chars().next());
        if matches!(state, Some('Z') | Some('X') | None) {
            return Err(err!(
                "The launcher {} ended before it installed the deletion meter.", pid;
                System, Missing));
        }
        {
            for e in rd.flatten() {
                let is = match std::fs::read_link(e.path()) {
                    Ok(l)  => l.as_os_str() == LISTENER_LINK,
                    Err(_) => false,
                };
                if !is {
                    continue;
                }
                let n: i32 = match e.file_name().to_string_lossy().parse() {
                    Ok(n)  => n,
                    Err(_) => continue,
                };
                let who = res!(Pid::from_raw(pid as i32).ok_or_else(|| err!(
                    "The launcher's process id {} is not one.", pid; Bug, Invalid)));
                let pfd = res!(pidfd_open(who, PidfdFlags::empty()).map_err(|e| err!(
                    "The hand could not open the launcher {} to take its listener: {}.",
                    pid, e; System, IO)));
                let fd = res!(pidfd_getfd(&pfd, n, PidfdGetfdFlags::empty()).map_err(|e| err!(
                    "The hand could not copy the deletion meter's listener from the launcher \
                    {}: {}.", pid, e; System, IO)));
                return Ok(fd);
            }
        }
        if std::time::Instant::now() > until {
            return Err(err!(
                "The launcher {} did not install the deletion meter within {} s, so the \
                command was not allowed to start.", pid, wait.as_secs(); System, Timeout));
        }
        std::thread::sleep(Duration::from_millis(2));
    }
}

/// Reads a NUL-terminated path from another process's memory.
#[cfg(target_os = "linux")]
fn read_path(pid: u32, addr: u64) -> Option<PathBuf> {
    use std::os::unix::ffi::OsStringExt;
    use std::os::unix::fs::FileExt;
    let f = match std::fs::File::open(fmt!("/proc/{}/mem", pid)) {
        Ok(f)  => f,
        Err(_) => return None,
    };
    let mut out: Vec<u8> = Vec::new();
    let mut at = addr;
    while out.len() < PATH_READ_MAX {
        // Never across a page: the next one may not be mapped.
        let room = (4096 - (at % 4096)) as usize;
        let mut buf = vec![0u8; room.min(PATH_READ_MAX - out.len())];
        let n = match f.read_at(&mut buf, at) {
            Ok(0) | Err(_) => return None,
            Ok(n)          => n,
        };
        if let Some(z) = buf[..n].iter().position(|b| *b == 0) {
            out.extend_from_slice(&buf[..z]);
            return Some(PathBuf::from(std::ffi::OsString::from_vec(out)));
        }
        out.extend_from_slice(&buf[..n]);
        at += n as u64;
    }
    None
}

/// The absolute path a call named, resolved the way the kernel will.
#[cfg(target_os = "linux")]
fn resolve(pid: u32, dirfd: i32, addr: u64) -> Option<PathBuf> {
    let p = match read_path(pid, addr) {
        Some(p) => p,
        None    => return None,
    };
    let full = if p.is_absolute() {
        p
    } else {
        let link = if dirfd == AT_FDCWD {
            fmt!("/proc/{}/cwd", pid)
        } else {
            fmt!("/proc/{}/fd/{}", pid, dirfd)
        };
        match std::fs::read_link(link) {
            Ok(base) => base.join(p),
            Err(_)   => return None,
        }
    };
    let mut clean = PathBuf::new();
    for c in full.components() {
        match c {
            Component::CurDir		=> (),
            Component::ParentDir	=> { clean.pop(); },
            other					=> clean.push(other.as_os_str()),
        }
    }
    // The last name is what the call acts on and is never followed; the directory
    // holding it is, so it is resolved.
    match (clean.parent(), clean.file_name()) {
        (Some(dir), Some(name)) => match dir.canonicalize() {
            Ok(d)  => Some(d.join(name)),
            Err(_) => Some(clean.clone()),
        },
        _ => Some(clean),
    }
}

/// Answers one run's held calls until the last process holding the filter has gone.
///
/// Runs on a thread of its own, because receiving a notification blocks.
///
/// # Arguments
/// * `fd` - The listener, copied out of the launcher.
/// * `w` - The run's marks, budget and trash.
/// * `tx` - Where the held question and the readable refusals go.
/// * `sigtx` - The run's supervisor, told to kill the group when the user says stop.
/// * `answers` - The user's answers to a held question: true to go on.
/// * `tally` - What was counted, for [`Resp::Metered`].
#[cfg(target_os = "linux")]
pub fn watch(
    fd:      std::os::fd::OwnedFd,
    w:       Watch,
    tx:      tokio::sync::mpsc::Sender<Resp>,
    sigtx:   tokio::sync::mpsc::UnboundedSender<Sig>,
    answers: std::sync::mpsc::Receiver<bool>,
    tally:   Arc<Tally>,
) {
    use libseccomp::{
        ScmpNotifReq,
        ScmpNotifResp,
        ScmpNotifRespFlags,
        ScmpSyscall,
    };
    use rustix::event::{
        poll,
        PollFd,
        PollFlags,
        Timespec,
    };
    use std::os::fd::AsRawFd;

    let raw = fd.as_raw_fd();
    let named = |n: &str| ScmpSyscall::from_name(n).ok();
    let (unlink, unlinkat, rmdir) = (named("unlink"), named("unlinkat"), named("rmdir"));
    let (rename, renameat, renameat2) = (named("rename"), named("renameat"), named("renameat2"));

    let mut judge = Judge::new(w.marks.clone(), w.caches.clone(), w.since);
    let mut allowed = false;
    let mut notes: HashSet<PathBuf> = HashSet::new();
    let mut sample: Vec<String> = Vec::new();
    let tick = Timespec { tv_sec: 0, tv_nsec: 250_000_000 };

    let answer = |id: u64, errno: i32| {
        let r = if errno == 0 {
            ScmpNotifResp::new_continue(id, ScmpNotifRespFlags::empty())
        } else {
            ScmpNotifResp::new_error(id, -errno, ScmpNotifRespFlags::empty())
        };
        // The caller may have died meanwhile; nothing is owed to it.
        let _ = r.respond(raw);
    };

    loop {
        let mut fds = [PollFd::new(&fd, PollFlags::IN)];
        match poll(&mut fds, Some(&tick)) {
            Ok(0)  => continue,
            Ok(_)  => (),
            Err(_) => continue,
        }
        let rev = fds[0].revents();
        if rev.contains(PollFlags::HUP) && !rev.contains(PollFlags::IN) {
            break; // Nothing holds the filter any more.
        }
        let req = match ScmpNotifReq::receive(raw) {
            Ok(r)  => r,
            Err(_) => continue, // The caller died between the poll and the receive.
        };
        let sc = Some(req.data.syscall);
        let a = req.data.args;
        let pid = req.pid;
        let path_at = |dfd: u64, addr: u64| resolve(pid, dfd as u32 as i32, addr);

        let verdict = if sc == unlink || sc == rmdir {
            path_at(AT_FDCWD as u32 as u64, a[0]).map(|p| judge.remove(&p, sc == rmdir))
        } else if sc == unlinkat {
            path_at(a[0], a[1]).map(|p| judge.remove(&p, a[2] & AT_REMOVEDIR != 0))
        } else if sc == rename {
            match (path_at(AT_FDCWD as u32 as u64, a[0]), path_at(AT_FDCWD as u32 as u64, a[1])) {
                (Some(f), Some(t)) => Some(judge.rename(&f, &t, 0)),
                _ => None,
            }
        } else if sc == renameat || sc == renameat2 {
            // Only `renameat2` carries flags; `renameat`'s fifth register is whatever was left there.
            let flags = if sc == renameat2 { a[4] } else { 0 };
            match (path_at(a[0], a[1]), path_at(a[2], a[3])) {
                (Some(f), Some(t)) => Some(judge.rename(&f, &t, flags)),
                _ => None,
            }
        } else {
            Some(Verdict::Go)
        };

        // The path was read from memory the caller could have changed; a request the
        // kernel no longer knows is one whose answer means nothing.
        if libseccomp::notify_id_valid(raw, req.id).is_err() {
            continue;
        }

        let verdict = match verdict {
            Some(v) => v,
            // Unreadable: refused rather than guessed at.
            None    => { answer(req.id, libc_eperm()); continue; },
        };

        match verdict {
            Verdict::Go   => answer(req.id, 0),
            Verdict::Xdev => answer(req.id, libc_exdev()),
            Verdict::Root(p) => {
                // Said before the answer, so it reaches the page before the command's end.
                if notes.len() < NOTES_MAX && notes.insert(p.clone()) {
                    let _ = tx.blocking_send(Resp::Error {
                        id:      Some(w.id.clone()),
                        message: fmt!(
                            "The hand refused to remove or move {}: it is a root this command \
                            was given (a Diamond's folder, or the folder the hand was granted), \
                            or it holds one, and a root cannot be removed or moved away by a \
                            command. Remove what is inside it instead, if that is what was \
                            meant.", p.display()),
                    });
                }
                answer(req.id, libc_eperm());
            },
            Verdict::Count(victim, mark) => {
                if tally.stopped.load(Ordering::Relaxed) {
                    answer(req.id, libc_eperm());
                    continue;
                }
                let spent = tally.counted.load(Ordering::Relaxed);
                if spent >= w.budget && !allowed {
                    // Held: the call is not answered until the user says.
                    let _ = tx.blocking_send(Resp::Held {
                        id:      w.id.clone(),
                        counted: spent,
                        sample:  sample.clone(),
                        mark:    fmt!("{}", mark.display()),
                        since_ms: w.since_ms,
                    });
                    let go = matches!(
                        answers.recv_timeout(Duration::from_millis(HOLD_MS)), Ok(true));
                    if go {
                        allowed = true;
                    } else {
                        tally.stopped.store(true, Ordering::Relaxed);
                        let _ = tx.blocking_send(Resp::Error {
                            id:      Some(w.id.clone()),
                            message: fmt!(
                                "The hand stopped this command. It had removed {} files in {} \
                                that existed before this turn -- the most a turn may remove \
                                without asking -- and the user did not let it go on. Those \
                                files are in the hand's trash and the user can put them back. \
                                Do not try to remove them another way.",
                                spent, mark.display()),
                        });
                        answer(req.id, libc_eperm());
                        let _ = sigtx.send(Sig::Kill);
                        continue;
                    }
                }
                match keep(&w.trash, w.since_ms, &victim) {
                    Ok(()) => {
                        tally.counted.fetch_add(1, Ordering::Relaxed);
                        if sample.len() < SAMPLE_MAX {
                            sample.push(fmt!("{}", victim.display()));
                        }
                        answer(req.id, 0);
                    },
                    Err(e) => {
                        // Said, like a root's refusal: a bare "Operation not permitted" names
                        // no cause, and a model reading one tries the removal another way.
                        if notes.len() < NOTES_MAX && notes.insert(victim.clone()) {
                            let _ = tx.blocking_send(Resp::Error {
                                id:      Some(w.id.clone()),
                                message: fmt!(
                                    "The hand refused to remove {}, because it must keep a file \
                                    before a command removes it and could not: {}.",
                                    victim.display(), e.msgs().join(" ")),
                            });
                        }
                        answer(req.id, libc_eperm());
                    },
                }
            },
        }
    }
}

#[cfg(target_os = "linux")]
fn libc_eperm() -> i32 { rustix::io::Errno::PERM.raw_os_error() }

#[cfg(target_os = "linux")]
fn libc_exdev() -> i32 { rustix::io::Errno::XDEV.raw_os_error() }

// ┌───────────────────────────────────────────────────────────────┐
// │ Tests                                                          │
// └───────────────────────────────────────────────────────────────┘

#[cfg(test)]
mod tests {
    use super::*;

    /// A fresh fixture directory, in the slot's own corner of the home cache: never `/tmp`,
    /// and never under a toolchain folder the hand exempts from the meter.
    fn tree(name: &str) -> Outcome<PathBuf> {
        let home = res!(std::env::var("HOME").map_err(|e| err!(e, "No HOME."; Test)));
        let slot = std::env::var("RC_SLOT").unwrap_or_else(|_| fmt!("solo"));
        let dir = PathBuf::from(home).join(".cache/daimond-handdelete").join(slot)
            .join("meter-unit").join(name);
        let _ = std::fs::remove_dir_all(&dir);
        res!(std::fs::create_dir_all(&dir));
        Ok(res!(dir.canonicalize()))
    }

    /// **The judge counts what the design says and frees what it says.**
    #[test]
    fn the_judge_counts_old_files_and_frees_the_rest() -> Outcome<()> {
        let base = res!(tree("judge"));
        let mark = base.join("mark");
        res!(std::fs::create_dir_all(mark.join("src")));
        res!(std::fs::create_dir_all(mark.join("target/debug")));
        res!(std::fs::create_dir_all(mark.join("node_modules/x")));
        res!(std::fs::write(mark.join("target/CACHEDIR.TAG"), "Signature: 8a477f597d28d172789f06886806bc55"));
        for f in ["src/a.rs", "target/debug/o", "node_modules/x/i.js"] {
            res!(std::fs::write(mark.join(f), "x"));
        }
        let later = SystemTime::now() + Duration::from_secs(3600);
        let mut j = Judge::new(vec![mark.clone()], Vec::new(), later);
        let old = mark.join("src/a.rs");
        assert_eq!(Verdict::Count(old.clone(), mark.clone()), j.remove(&old, false));
        assert_eq!(Verdict::Go, j.remove(&mark.join("src"), true), "rmdir is free");
        assert_eq!(Verdict::Go, j.remove(&mark.join("target/debug/o"), false));
        assert_eq!(Verdict::Go, j.remove(&mark.join("node_modules/x/i.js"), false));
        assert_eq!(Verdict::Root(mark.clone()), j.remove(&mark, true));
        assert_eq!(Verdict::Root(base.clone()), j.rename(&base, &base.join("x"), 0));
        assert_eq!(Verdict::Go, j.remove(&base.join("outside.txt"), false));
        // Renames: within the counted zone free, out of it EXDEV.
        assert_eq!(Verdict::Go, j.rename(&old, &mark.join("src/b.rs"), 0));
        assert_eq!(Verdict::Xdev, j.rename(&old, &mark.join("target/b.rs"), 0));
        assert_eq!(Verdict::Xdev, j.rename(&old, &base.join("b.rs"), 0));
        // Born this turn: free.
        let earlier = SystemTime::now() - Duration::from_secs(3600);
        let mut j = Judge::new(vec![mark.clone()], Vec::new(), earlier);
        assert_eq!(Verdict::Go, j.remove(&old, false));
        Ok(())
    }

    /// **A rename onto a file that was there before the turn counts that file (audit F3).**
    ///
    /// `mv -f <new> <old>` destroys `<old>` as surely as `rm` does.  Keyed on the source
    /// alone, the judge let it through, because the source was born this turn.
    #[test]
    fn a_rename_over_an_old_file_counts_the_old_file() -> Outcome<()> {
        let base = res!(tree("rename-over"));
        let mark = base.join("mark");
        res!(std::fs::create_dir_all(mark.join("src")));
        res!(std::fs::create_dir_all(mark.join("target")));
        res!(std::fs::write(mark.join("target/CACHEDIR.TAG"), "Signature: 8a477f597d28d172789f06886806bc55"));
        let old = mark.join("src/keep.txt");
        res!(std::fs::write(&old, "kept"));
        res!(std::fs::write(mark.join("target/o"), "o"));
        let twin = mark.join("src/twin.txt");
        res!(std::fs::hard_link(&old, &twin));
        // The turn begins between the old files and the new ones.
        std::thread::sleep(Duration::from_millis(20));
        let since = SystemTime::now();
        std::thread::sleep(Duration::from_millis(20));
        let new = mark.join("src/new.tmp");
        let newer = mark.join("src/newer.tmp");
        let outside = base.join("outside.tmp");
        for f in [&new, &newer, &outside] {
            res!(std::fs::write(f, "junk"));
        }
        let mut j = Judge::new(vec![mark.clone()], Vec::new(), since);
        // Over an old file, from inside the mark or from outside every mark: counted.
        assert_eq!(Verdict::Count(old.clone(), mark.clone()), j.rename(&new, &old, 0));
        assert_eq!(Verdict::Count(old.clone(), mark.clone()), j.rename(&outside, &old, 0));
        // The two renameat2 flags that lose nothing.
        assert_eq!(Verdict::Go, j.rename(&new, &old, RENAME_EXCHANGE));
        assert_eq!(Verdict::Go, j.rename(&new, &old, RENAME_NOREPLACE));
        // Onto a file born this turn, into a cache, or onto nothing: free.
        assert_eq!(Verdict::Go, j.rename(&new, &newer, 0));
        assert_eq!(Verdict::Go, j.rename(&new, &mark.join("target/o"), 0));
        assert_eq!(Verdict::Go, j.rename(&new, &mark.join("src/absent.txt"), 0));
        // Two names for one inode, which the kernel renames as nothing at all.
        assert_eq!(Verdict::Go, j.rename(&twin, &old, 0));
        // An exchange that would carry an old file into a cache launders it, as a move does.
        assert_eq!(Verdict::Xdev, j.rename(&mark.join("target/o"), &old, RENAME_EXCHANGE));
        // And a root is not replaced, whichever side names it.
        assert_eq!(Verdict::Root(mark.clone()), j.rename(&new, &mark, 0));
        Ok(())
    }

    /// **A cache a mark holds is free; a mark a cache holds is counted (audit F5).**
    #[test]
    fn a_cache_inside_a_mark_is_free_and_a_mark_inside_a_cache_is_not() -> Outcome<()> {
        let base = res!(tree("caches"));
        let home = base.join("home");
        let cache = home.join(".cache/cargo-targets");
        let worlds = home.join(".cache/daimond");
        let proj = worlds.join("proj");
        for d in [&cache.join("slot/debug"), &proj] {
            res!(std::fs::create_dir_all(d));
        }
        let built = cache.join("slot/debug/o");
        let notes = home.join("notes.txt");
        let work = proj.join("work.txt");
        for f in [&built, &notes, &work] {
            res!(std::fs::write(f, "x"));
        }
        let later = SystemTime::now() + Duration::from_secs(3600);
        // A granted home directory holds every cache: the cache is free, the rest counted.
        let mut j = Judge::new(vec![home.clone()], vec![cache.clone(), worlds.clone()], later);
        assert_eq!(Verdict::Go, j.remove(&built, false));
        assert_eq!(Verdict::Count(notes.clone(), home.clone()), j.remove(&notes, false));
        // A Diamond's folder kept inside a cache is the user's work.
        let mut j = Judge::new(vec![proj.clone()], vec![cache.clone(), worlds.clone()], later);
        assert_eq!(Verdict::Count(work.clone(), proj.clone()), j.remove(&work, false));
        Ok(())
    }

    /// **A file the trash cannot link is copied only while it is small, and never through a
    /// link (audit F6).**
    ///
    /// `copy_kept` is what `keep` falls back to when the hard link fails -- a mark on another
    /// filesystem -- and it is called directly here, because a second filesystem is not
    /// something a unit test can count on having.  `dev/verify_handdelete.mjs` drives the real
    /// fallback, through the kernel, where one exists.
    #[test]
    fn a_file_the_trash_cannot_link_is_copied_only_while_small() -> Outcome<()> {
        let base = res!(tree("copy-kept"));
        let trash = base.join("trash");
        res!(std::fs::create_dir_all(&trash));
        let small = base.join("small.txt");
        let big = base.join("big.bin");
        res!(std::fs::write(&small, "kept"));
        res!(std::fs::write(&big, vec![0u8; (COPY_MAX + 1) as usize]));
        res!(copy_kept(&small, &trash.join("small.txt")));
        assert_eq!("kept", res!(std::fs::read_to_string(trash.join("small.txt"))));
        // Over the ceiling: refused, saying why, and nothing half-copied left behind.
        match copy_kept(&big, &trash.join("big.bin")) {
            Ok(()) => panic!("a file over COPY_MAX was copied"),
            Err(e) => assert!(e.msgs().join(" ").contains("copies nothing over"), "{}", e),
        }
        assert!(std::fs::symlink_metadata(trash.join("big.bin")).is_err(),
            "a refused copy left a file in the trash");
        // A link is kept as the link it is, and not as the large file it points at.
        let link = base.join("link");
        res!(std::os::unix::fs::symlink(&big, &link));
        res!(copy_kept(&link, &trash.join("link")));
        let kept = res!(std::fs::symlink_metadata(trash.join("link")));
        assert!(kept.file_type().is_symlink(), "a link was kept as what it points at");
        assert_eq!(big, res!(std::fs::read_link(trash.join("link"))));
        Ok(())
    }

    /// **A kept file comes back, and one whose place is taken again stays kept.**
    #[test]
    fn the_trash_puts_back_what_it_took() -> Outcome<()> {
        let base = res!(tree("trash"));
        let trash = base.join("trash");
        let a = base.join("mark/a.txt");
        let b = base.join("mark/sub/b.txt");
        res!(std::fs::create_dir_all(base.join("mark/sub")));
        res!(std::fs::write(&a, "a"));
        res!(std::fs::write(&b, "b"));
        res!(keep(&trash, 42, &a));
        res!(keep(&trash, 42, &b));
        res!(std::fs::remove_file(&a));
        res!(std::fs::remove_dir_all(base.join("mark/sub")));
        res!(std::fs::write(&a, "new"));
        let (put, left) = res!(restore(&trash, 42));
        assert_eq!((1, 1), (put, left));
        assert_eq!("b", res!(std::fs::read_to_string(&b)));
        assert_eq!("new", res!(std::fs::read_to_string(&a)));
        Ok(())
    }
}
